### ISSUE TITLE
Cannot defer ending a top-level turn

### ISSUE THREAD

**Issue by arjunguha** [plasma-umass/Stopify#350]
This test fails. Maybe it's okay?

```
<html>
<body>
<script src="../../dist/stopify-full.bundle.js"></script>
<script>
function sleep(duration) {
  asyncRun.pauseImmediate(() => {
    window.setTimeout(() => asyncRun.continueImmediate(undefined), duration);
  });
}

const program = `
  sleep(50);
`;

const asyncRun = stopify.stopifyLocally(
  `(function(){ ${program} })()`,
  { externals: [ 'sleep' ] });

var i = 0;
asyncRun.run(() => {
  i = i + 1;
  // Give the code time to call onDone again.
  window.setTimeout(() => {
    if (i === 1) {
      throw `onDone called ${i} times (expected 1 call)`;
    }
    window.document.title = 'okay';
  }, 1000);
});
if (i > 0) {
  throw 'onDone called immediately, not after sleep';
}

window.onerror = function() {
  window.document.title = "error";
}

</script>
</body>
</html>
```

**Comment by baxtersa** [comment]
I am guessing that `onDone` is being called when `sleep` suspends to the top level and adds an event to the `eventQueue`. When this happens, the remaining delimited continuations are processed anyway because they're not captured by the continuation of the `sleep` statement, and the delimit stack is processed separately from `eventQueue`. Is my understanding correct?

**Comment by baxtersa** [comment]
I just realized, this is a limitation of `async/await` as well. You can only `await` within an `async`-annotated function, so the equivalent of the above example would have to be
```js
async function F() {
  await sleep(50);
}

F();    // Returns a promise.
```

The `async/await` solution is self-documenting and can yell at you for not doing this, where our API is _too clean_.

**Comment by arjunguha** [comment]
This is fixed.
