### ISSUE TITLE
Looking for integrating Stopify with my project

### ISSUE THREAD

**Issue by thangngoc89** [plasma-umass/Stopify#407]
Hello folks,

A friend of mine just sent me a link to Stopify and after reading through the FAQ, I was just mind-blowing about what Stopify can do. 

I'm building a thing called [Sketch.sh](https://sketch.sh) which is an open source playground for evaluating OCaml/ReasonML code in browser. I have to implement many things to avoid infinite loops and keeping the main thread responsive. But the OCaml example kills it so easily ! (freeze the browser's tab completely even though it runs inside a web worker)

Furthermore, there have been a few requests for me to allow DOM access for plotting, graphics programing , ... (which problematic inside Web Worker). And Stopify even address that ! 

So I'm super excited to integrate Stopify to Sketch and I would love to know more about Spotify and how easy it is to integrate with OCaml's compiler. 
THank you very much

**Comment by baxtersa** [comment]
Hi @thangngoc89, thanks for the kind words! I checked out Sketch.sh, it looks very cool too!

Integrating Stopify should definitely be doable. Stopify has a mode which let's you input JavaScript code as a `string` and compiles it in the browser. This means you should be able to take the output of your OCaml compiler (stopify.org uses bucklescript, but js_of_ocaml should also work if you use that), pass this into the Stopify compiler, and receive an `AsyncRun` object, which contains the instrumented JavaScript, and knows how to launch the program within the Stopify runtime.

You can find more instructive documentation [here](https://stopify.readthedocs.io/en/0.5.0/index.html) if you haven't seen it yet, [stopify.org](https://www.stopify.org) uses older interfaces and is a little light on integration details. The docs contain a couple examples of integrating Stopify into a single webpage that might be insightful when getting started. You can also compile with Stopify in Node.js if you run you OCaml compiler on a server and prefer to do that.

Feel free to reach out if you have more questions along the way. I don't have many spare cycles to dig into the Sketch.sh codebase, but I am happy to debug Stopify issues you run into.

**Comment by thangngoc89** [comment]
Thank you for your quick responses. And looks like I had a wrong understanding about how Stopify works. 

Correct me if I'm wrong but are you saying that I can take the code outputed by jsoo (I'm using it instead of Bucklescript) 

![image](https://user-images.githubusercontent.com/3049054/45266352-225cf400-b484-11e8-9ecd-e58380df20f0.png)

([See the demo here](http://ocsigen.org/js_of_ocaml/toplevel.html#version=4.06.0))

and feed it into stopify -> executing it with stopify api right? so all jsoo's features are supported

**Comment by thangngoc89** [comment]
Thank you for your answer.I'll have a closer look of how things works tomorrow. I'm not super familiar with jsoo's internal but AFAIK, there is a global object called `jsoo_runtime` that all generated code will use. 

This enables many features like separate compilation: you can compile a library separately and hot load it into the runtime.

Example: https://libraries.sketch.sh/owl_base.loader.sketch.js .

So do I need to compile the jsoo compiler with spotify ? Or just the compied Javascript code from jsoo?

**Comment by baxtersa** [comment]
Sorry for the long delay here.

Stopify unfortunately doesn't work seamlessly with separate compilation toolchains - it's a whole program transformation that must be able to reach and instrument all transitive dependencies at compile time. This would be really useful, but isn't likely to happen in the near term.

Regarding jsoo specifically, the jsoo _compiler_ doesn't have to be compiled with stopify, just the runtime dependencies of the compiled JavaScript code from jsoo (as well as the jsoo compiled code itself). I am not familiar with how jsoo packages or implements it's runtime. If `jsoo_runtime` methods are implemented in JS, these methods are what need to be compiled with Stopify as well. If jsoo implements an interpreter and the `jsoo_runtime` methods are ocaml bytecode, the interpreter would also need to be compiled with Stopify. Sorry I can't be of much more help since I'm not familiar with jsoo internals.

Let me know if you're still investigating this - I can leave this issue open. If you're no longer pursuing this path, I'll close this issue and we can reopen if it pops up again.

**Comment by thangngoc89** [comment]
@baxtersa Thank you for your input, while this is the right path for my project, it's extremely hard to pursue since I have knowledges of jsoo's internal either.
