### ISSUE TITLE
Use and export path.scope.generateUid(_) for generated variables

### ISSUE THREAD

**Issue by rachitnigam** [plasma-umass/Stopify#6]
We should prefix all generated variables with `$` to avoid capture and make it easier to debug later down the line.

**Comment by baxtersa** [comment]
What does `$` have to do with anything?

**Comment by arjunguha** [comment]
having a common prefix is fine. but i encourage you to get capture-avoiding name generating right, sooner rather than later. i.e., you cannot assume that the program doesn't use `$` in variable names

**Comment by rachitnigam** [comment]
@arjunguha All variable names generated by babel are capture avoiding. 
@baxtersa This is just for variables that we are using in the stopify functions. `counter` might be way too common and get captured. Also, this is going to be helpful for debugging and the debugger we we name all generated functions with `$` since a user should never be seeing something starting with `$`.

**Comment by baxtersa** [comment]
@rachitnigam , the point is that we can't assume a user should never be seeing something starting with `$`. It's perfectly valid for people to do that.

Really, we need a way of generating unique identifiers for our `counter`/`$isFree`/`$isGen`/etc. properties that we inject code to tag objects with. We should be able to do this using `path.scope.generateUid` during our transforms. We'll need to export these Uid variables so that we can access them from the stoppable objects.

I've changed the Issue to reflect what's needed.

**Comment by rachitnigam** [comment]
Closing this for now. I know we haven't fixed this but it seems highly unlikely that we will have a naming conflict and we'll probably not get around fixing this.

Even if we do, we can add a `R00t_1337__` prefix to all our variable names.
